name: vehicletracking
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_svg: ^1.1.4
  http: ^0.13.5
  provider: ^6.0.4
  get_storage: ^2.0.2
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.3
  workmanager: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/png/
    - assets/image/svg/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900        
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 800        
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 700        
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600        
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500        
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400        
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300        
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200        
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100        
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
